import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Fira_Sans } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StoreProvider } from './storeProvider';

const inter = Inter({ subsets: ['latin'] });
const fira_sans = Fira_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'EventZenith',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={fira_sans.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
